export const STEPS = [
  {
    number: 1,
    title: 'Seña',
    subtitle: 'Depósito en garantía',
    description: 'El comprador deposita la seña que queda retenida hasta que los informes estén OK.',
    icon: '💰',
    color: '#6366f1',
    tag: 'Automático',
    instructions: [
      'Acordá el monto de la seña con el vendedor',
      'Depositá la seña a través de la plataforma',
      'La seña queda retenida hasta que los informes confirmen que está todo bien',
      'Si hay problemas con el auto, se te devuelve la seña completa',
    ],
  },
  {
    number: 2,
    title: 'Informes DNRPA',
    subtitle: 'Verificación de dominio',
    description: 'Se piden informes del auto: inhibiciones, embargos, prendas. Si está todo limpio, avanzamos.',
    icon: '📋',
    color: '#f59e0b',
    tag: 'Vos',
    instructions: [
      'Ingresá a la web de DNRPA (te damos el link directo)',
      'Pedí el informe de dominio del vehículo',
      'Pagá el informe con BEP (te guiamos paso a paso)',
      'Subí el PDF del informe acá',
      'Nosotros lo analizamos y te decimos si está limpio',
    ],
  },
  {
    number: 3,
    title: 'Multas y Patentes',
    subtitle: 'Verificación de deudas',
    description: 'Chequeamos multas pendientes y deuda de patentes para que no haya sorpresas después.',
    icon: '🔍',
    color: '#3b82f6',
    tag: 'Automático',
    instructions: [
      'Consultá las multas en la web de tu jurisdicción',
      'Verificá el estado de patentes del vehículo',
      'Ingresá los montos de deuda encontrados (si hay)',
      'Las deudas se descuentan del precio o las paga el vendedor antes de la transferencia',
    ],
  },
  {
    number: 4,
    title: 'Verificación Policial',
    subtitle: 'VPA del vehículo',
    description: 'Se saca turno para la verificación policial. Sacale foto al título y completamos todo automáticamente.',
    icon: '🔒',
    color: '#22c55e',
    tag: 'Vos',
    instructions: [
      'Sacá una foto clara del título del auto (frente y dorso)',
      'La app autocompleta los datos para el turno de VPA',
      'Te asignamos el turno más cercano disponible',
      'Llevá el auto a la planta verificadora en la fecha indicada',
      'Una vez hecha, marcá como completada',
    ],
  },
  {
    number: 5,
    title: 'Turno en Registro',
    subtitle: 'Registro seccional',
    description: 'Sacamos turno en el registro que corresponde para hacer la transferencia.',
    icon: '📅',
    color: '#6366f1',
    tag: 'Automático',
    instructions: [
      'La app determina el registro seccional correspondiente',
      'Se saca turno automáticamente para la fecha más próxima',
      'Ambas partes reciben la confirmación del turno',
      'Preparar: DNI original, título, formularios 08 y CETA',
    ],
  },
  {
    number: 6,
    title: 'Pago + Transferencia',
    subtitle: 'Cierre de operación',
    description: 'Se coordina el encuentro, se paga el auto y se firma en el registro. ¡Listo!',
    icon: '🎉',
    color: '#22c55e',
    tag: 'Vos',
    instructions: [
      'Coordiná el lugar de encuentro con el vendedor',
      'Realizá el pago del auto (te recomendamos transferencia bancaria)',
      'Asistí al registro con toda la documentación',
      'Firmá el formulario 08 y completá la transferencia',
      '¡Felicitaciones! El auto es tuyo legalmente',
    ],
  },
] as const

export type StepStatus = 'pending' | 'in_progress' | 'completed' | 'blocked'
export type OperationStatus = 'active' | 'completed' | 'cancelled'
export type UserRole = 'buyer' | 'seller'
